[package]
name = "myth_egui"
description = "Myth-native egui integration without depending on egui-wgpu."
keywords.workspace = true
categories.workspace = true
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
myth_assets = { workspace = true }
myth_render = { workspace = true }

bytemuck = { workspace = true }
egui = { workspace = true }
epaint = { workspace = true }
log = { workspace = true }
rustc-hash = { workspace = true }
winit = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
egui-winit = { workspace = true }
wgpu = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
egui-winit = { workspace = true, default-features = false, features = ["links"] }
wgpu = { workspace = true, features = ["webgpu", "fragile-send-sync-non-atomic-wasm"] }

[lints]
workspace = true
